-- ============================================================
-- CELLI CRUZ - Supabase schema
-- Execute no SQL Editor do projeto Supabase
-- ============================================================

create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.site_config (
  id smallint primary key default 1,
  nome_empresa text,
  telefone text,
  whatsapp text,
  whatsapp_vendas text,
  whatsapp_atendimento text,
  email text,
  endereco text,
  hero_chamada text,
  hero_subtitulo text,
  google_maps_embed text,
  updated_at timestamptz not null default now(),
  constraint site_config_singleton check (id = 1)
);

create table if not exists public.site_about (
  id smallint primary key default 1,
  about_title text,
  about_subtitle text,
  about_description text,
  about_summary text,
  about_mission_title text,
  about_mission_text text,
  mission_gallery text[] not null default '{}',
  updated_at timestamptz not null default now(),
  constraint site_about_singleton check (id = 1)
);

create table if not exists public.about_mission_carousel (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  image_desktop text,
  image text,
  image_source text,
  image_mobile text,
  image_mobile_source text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.carousel_items (
  id bigint generated by default as identity primary key,
  title text,
  subtitle text,
  image_desktop text,
  image text,
  image_source text,
  image_mobile text,
  image_mobile_source text,
  link text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.whatsapp_options (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  whatsapp text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.imoveis (
  id bigint generated by default as identity primary key,
  destaque boolean not null default false,
  nome text not null,
  bairro text,
  cidade text,
  quartos smallint,
  metragem text,
  descricao text,
  tag text,
  imagem text,
  imagem_source text,
  imagem_galeria text[] not null default '{}',
  diferenciais text[] not null default '{}',
  localizacao text,
  maps_link text,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.imovel_plantas (
  id bigint generated by default as identity primary key,
  imovel_id bigint not null references public.imoveis(id) on delete cascade,
  nome text,
  descricao text,
  unidades smallint,
  sort_order integer not null default 0
);

create table if not exists public.imovel_comodos (
  id bigint generated by default as identity primary key,
  imovel_id bigint not null references public.imoveis(id) on delete cascade,
  nome text,
  fotos text[] not null default '{}'
);

create index if not exists idx_about_mission_carousel_sort on public.about_mission_carousel(sort_order, id);
create index if not exists idx_carousel_items_sort on public.carousel_items(sort_order, id);
create index if not exists idx_imoveis_destaque on public.imoveis(destaque) where destaque = true;
create index if not exists idx_imoveis_status on public.imoveis(status);
create index if not exists idx_imoveis_bairro on public.imoveis(bairro);
create index if not exists idx_imovel_plantas_imovel on public.imovel_plantas(imovel_id, sort_order, id);
create index if not exists idx_imovel_comodos_imovel on public.imovel_comodos(imovel_id, id);

drop trigger if exists trg_site_config_touch on public.site_config;
create trigger trg_site_config_touch
before update on public.site_config
for each row execute function public.touch_updated_at();

drop trigger if exists trg_site_about_touch on public.site_about;
create trigger trg_site_about_touch
before update on public.site_about
for each row execute function public.touch_updated_at();

drop trigger if exists trg_imoveis_touch on public.imoveis;
create trigger trg_imoveis_touch
before update on public.imoveis
for each row execute function public.touch_updated_at();

insert into public.site_config (id)
values (1)
on conflict (id) do nothing;

insert into public.site_about (id)
values (1)
on conflict (id) do nothing;

alter table public.site_config enable row level security;
alter table public.site_about enable row level security;
alter table public.about_mission_carousel enable row level security;
alter table public.carousel_items enable row level security;
alter table public.whatsapp_options enable row level security;
alter table public.imoveis enable row level security;
alter table public.imovel_plantas enable row level security;
alter table public.imovel_comodos enable row level security;

drop policy if exists "public read site_config" on public.site_config;
create policy "public read site_config"
on public.site_config
for select
using (true);

drop policy if exists "public read site_about" on public.site_about;
create policy "public read site_about"
on public.site_about
for select
using (true);

drop policy if exists "public read about_mission_carousel" on public.about_mission_carousel;
create policy "public read about_mission_carousel"
on public.about_mission_carousel
for select
using (true);

drop policy if exists "public read carousel_items" on public.carousel_items;
create policy "public read carousel_items"
on public.carousel_items
for select
using (true);

drop policy if exists "public read whatsapp_options" on public.whatsapp_options;
create policy "public read whatsapp_options"
on public.whatsapp_options
for select
using (true);

drop policy if exists "public read imoveis" on public.imoveis;
create policy "public read imoveis"
on public.imoveis
for select
using (true);

drop policy if exists "public read imovel_plantas" on public.imovel_plantas;
create policy "public read imovel_plantas"
on public.imovel_plantas
for select
using (true);

drop policy if exists "public read imovel_comodos" on public.imovel_comodos;
create policy "public read imovel_comodos"
on public.imovel_comodos
for select
using (true);

drop policy if exists "authenticated write site_config" on public.site_config;
create policy "authenticated write site_config"
on public.site_config
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write site_about" on public.site_about;
create policy "authenticated write site_about"
on public.site_about
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write about_mission_carousel" on public.about_mission_carousel;
create policy "authenticated write about_mission_carousel"
on public.about_mission_carousel
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write carousel_items" on public.carousel_items;
create policy "authenticated write carousel_items"
on public.carousel_items
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write whatsapp_options" on public.whatsapp_options;
create policy "authenticated write whatsapp_options"
on public.whatsapp_options
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write imoveis" on public.imoveis;
create policy "authenticated write imoveis"
on public.imoveis
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write imovel_plantas" on public.imovel_plantas;
create policy "authenticated write imovel_plantas"
on public.imovel_plantas
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "authenticated write imovel_comodos" on public.imovel_comodos;
create policy "authenticated write imovel_comodos"
on public.imovel_comodos
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;

drop policy if exists "public read uploads" on storage.objects;
create policy "public read uploads"
on storage.objects
for select
using (bucket_id = 'uploads');

drop policy if exists "authenticated insert uploads" on storage.objects;
create policy "authenticated insert uploads"
on storage.objects
for insert
with check (bucket_id = 'uploads' and auth.role() = 'authenticated');

drop policy if exists "authenticated update uploads" on storage.objects;
create policy "authenticated update uploads"
on storage.objects
for update
using (bucket_id = 'uploads' and auth.role() = 'authenticated')
with check (bucket_id = 'uploads' and auth.role() = 'authenticated');

drop policy if exists "authenticated delete uploads" on storage.objects;
create policy "authenticated delete uploads"
on storage.objects
for delete
using (bucket_id = 'uploads' and auth.role() = 'authenticated');

create or replace function public.sync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.about_mission_carousel', 'id'), coalesce((select max(id) from public.about_mission_carousel), 1), true);
  perform setval(pg_get_serial_sequence('public.carousel_items', 'id'), coalesce((select max(id) from public.carousel_items), 1), true);
  perform setval(pg_get_serial_sequence('public.whatsapp_options', 'id'), coalesce((select max(id) from public.whatsapp_options), 1), true);
  perform setval(pg_get_serial_sequence('public.imoveis', 'id'), coalesce((select max(id) from public.imoveis), 1), true);
  perform setval(pg_get_serial_sequence('public.imovel_plantas', 'id'), coalesce((select max(id) from public.imovel_plantas), 1), true);
  perform setval(pg_get_serial_sequence('public.imovel_comodos', 'id'), coalesce((select max(id) from public.imovel_comodos), 1), true);
end;
$$;

revoke all on function public.sync_identity_sequences() from public;
grant execute on function public.sync_identity_sequences() to service_role;
