FROM nginx:alpine

RUN apk add --no-cache openssl certbot \
    && mkdir -p /var/www/certbot /etc/nginx/ssl /etc/letsencrypt

COPY nginx-entrypoint.sh /docker-entrypoint.d/nginx-entrypoint.sh
RUN chmod +x /docker-entrypoint.d/nginx-entrypoint.sh

EXPOSE 80 443
ENTRYPOINT ["/docker-entrypoint.d/nginx-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
